### ISSUE TITLE
首次运行报错UnboundLocalError: local variable  'VISITED_TARGET_LIST' referenced before assignment

### ISSUE THREAD

**Issue by alwaystest18** [winezer0/DynaScan#2]
首次运行报以下错误
![accb046f27285e691cc39140ff80c1b](https://user-images.githubusercontent.com/11520372/159937793-fd366897-50e4-4deb-93af-b08cd0ca82b1.png)
看了下代码
![47624434e1d31d6cfa5481d80ae4ae7](https://user-images.githubusercontent.com/11520372/159938169-d7e16857-74ee-4873-b0dc-680c2630ee59.png)
在DynaScan.py的368行，如果visited_target_file_path存在就从文件中读取内容，看了下配置文件里visited_target_file_path
![image](https://user-images.githubusercontent.com/11520372/159938763-68990fec-a9c7-426c-b063-2460c9dcc88d.png)
因为默认是不存在runtime目录及这个文件的，所以VISITED_TARGET_LIST没有赋值，我这里加了一个else判断后运行正常
![image](https://user-images.githubusercontent.com/11520372/159939160-ec7b1d0a-71ac-4ec5-b37b-069110577250.png)

**Comment by winezer0** [comment]
您好,请问当前版本是否还有BUG，我刚刚测试了删除runtime目录，发现是正常运行的。

![image](https://user-images.githubusercontent.com/46115146/160109460-6eb9ddb4-e16f-4832-a3bf-e01132c29ea8.png)

**Comment by alwaystest18** [comment]
> 您好,请问当前版本是否还有BUG，我刚刚测试了删除runtime目录，发现是正常运行的。
> 
> ![image](https://user-images.githubusercontent.com/46115146/160109460-6eb9ddb4-e16f-4832-a3bf-e01132c29ea8.png)

我在代码中搜VISITED_TARGET_LIST，看到只有满足文件存在这个条件才会赋值，你可以搜下VISITED_TARGET_LIST，看看是否在你当前的版本中还有其他位置赋值了？

**Comment by winezer0** [comment]
当前版本已进行测试,未发现问题,在代码中也无赋值相关问题。
runtime目录文件会由logger进行调用自动生成。  
如果存在问题请检查from loguru import logger 中的loguru模块是否已安装。
脚本开发环境为Python3.8.5,未使用新版本特性，3.2+版本理论都可用。

**Comment by alwaystest18** [comment]
删除了之前的目录，重新clone了一下新版本，目前使用正常了
