### ISSUE TITLE
老哥，不支持动态备份文件扫描啊，是bug还是没有这个功能

### ISSUE THREAD

**Issue by ccc-f** [winezer0/DynaScan#5]
比如 abc.com/abc.zip 这种类型的备份文件，没有扫到。

**Comment by winezer0** [comment]
http://www.baidu.com/baidu.com/baidu.zip？ 规则 %DOMAIN%/%DOMAIN%.zip
还是 http://baidu.com/baidu.zip ???  规则 %DOMAIN%.zip
这两种模式都是支持的，但是需要自己填写一下规则。

**Comment by ccc-f** [comment]
ok,懂了。
