### ISSUE TITLE
扫描结果问题

### ISSUE THREAD

**Issue by gao-ze-min** [winezer0/DynaScan#7]
为什么扫描结果中有的url会有两个/
https://www.baidu.com//api/v2/login

**Comment by winezer0** [comment]
因为这一句规则：
/{re=exrex:(|%ACTUATOR-PROJECT%)}$/api/v2/login  <-->10

{re=exrex:(|%ACTUATOR-PROJECT%)}$ 会解析出一个为空的结果，这时候就变成了/(空)/api/v2/login

**Comment by winezer0** [comment]
已修复该问题。
